# Travis CI (https://travis-ci.org/) is a free Hosted
# Continuous Integration Platform for the Open Source Community.


language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pep8
install:
    - "pip install -r requirements.txt"
script:
    - tox -e $TOX_ENV
