# -*- coding: utf-8 -*-

# TICTACTOEXXL DEFAULTS
GAME_N_IN_A_ROW_DEFAULT = 3
GAME_NUM_PLAYERS_DEFAULT = 2

BOARD_DIM_X_DEFAULT = 3
BOARD_DIM_Y_DEFAULT = 3

PLAYER_1_NAME_DEFAULT = "PLAYER_1"
PLAYER_2_NAME_DEFAULT = "PLAYER_2"
PLAYER_1_MOVE_REPR_DEFAULT = "x"
PLAYER_2_MOVE_REPR_DEFAULT = "o"


# TICTACTOEXXL PACKAGE DETAILS & FUNCTIONS
VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_MICRO = 1


def get_version():
    return "%s" % (".".join(str(v) for v in [VERSION_MAJOR, VERSION_MINOR,
                                             VERSION_MICRO]))
